drop table GameTurns;
drop table GameCards;
drop table Cards;
drop table GamePlayers;
drop table Teams;
drop table Games;



CREATE TABLE Games(
	[ID] int IDENTITY(1,1) NOT NULL,
	[Name] nvarchar(50) not null,
	[Password] nvarchar(50) null default null,
	[HasStarted] bit not null default 0,
	[HasFinished] bit not null default 0,
	[NumPlayers] int not null,
	[CreatedOn] datetime not null default current_timestamp,
 CONSTRAINT [PK_Games] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE Teams(
	[ID] int IDENTITY(1,1) NOT NULL,
	[Name] nvarchar(20) not null,
 CONSTRAINT [PK_Teams] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE GamePlayers(
	[ID] int IDENTITY(1,1) NOT NULL,
	[GameID] int not null,
	[Name] nvarchar(50) not null,
	[UserID] nvarchar(128) not null,
	[PublicTeamID] int not null,
	[PrivateTeamID] int not null,
	[Notes] nvarchar(MAX) not null default '',
CONSTRAINT [PK_GamePlayers] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE Cards(
	[ID] int IDENTITY(1,1) NOT NULL,
	[Name] nvarchar(50) not null,
	[Value] int not null default 1,
	[TeamID] int not null,
	[IsEvent] bit not null,
	[NumberPerGame] int not null default 1,
	[Description] nvarchar(MAX) not null,
 CONSTRAINT [PK_Cards] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE GameCards(
	[ID] int IDENTITY(1,1) NOT NULL,
	[GameID] int not null,
	[CardID] int not null,
	[GamePlayerID] int null,
	[Position] int not null,
	[Discarded] bit not null default 0,
 CONSTRAINT [PK_GameCards] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]


CREATE TABLE GameTurns(
	[ID] int IDENTITY(1,1) NOT NULL,
	[GameID] int not null,
	[GameCardID] int not null,
	[Number] int not null
 CONSTRAINT [PK_GameTurns] PRIMARY KEY CLUSTERED 
(
	[ID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]





CREATE NONCLUSTERED INDEX [IX_Games_HasStarted] ON Games
(
	[HasStarted] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_Games_HasFinished] ON Games
(
	[HasFinished] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GamePlayers_GameID_Name] ON GamePlayers
(
	[GameID] ASC,
	[Name] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GamePlayers_UserID] ON GamePlayers
(
	[UserID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_Cards_IsEvent] ON Cards
(
	[IsEvent] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GameCards_GameID] ON GameCards
(
	[GameID] ASC,
	[Discarded] ASC,
	[Position] DESC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GameCards_CardID] ON GameCards
(
	[CardID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GameCards_GamePlayerID] ON GameCards
(
	[GamePlayerID] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO

CREATE NONCLUSTERED INDEX [IX_GameTurns_GameID_Number] ON GameTurns
(
	[GameID] ASC,
	[Number]
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, SORT_IN_TEMPDB = OFF, DROP_EXISTING = OFF, ONLINE = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
GO





ALTER TABLE GamePlayers WITH CHECK ADD  CONSTRAINT [FK_GamePlayers_Games] FOREIGN KEY([GameID])
REFERENCES [Games] ([ID])
GO

ALTER TABLE GamePlayers WITH CHECK ADD  CONSTRAINT [FK_GamePlayers_AspNetUsers] FOREIGN KEY([UserID])
REFERENCES [AspNetUsers] ([ID])
GO

ALTER TABLE GamePlayers WITH CHECK ADD  CONSTRAINT [FK_GamePlayers_Teams_Public] FOREIGN KEY([PublicTeamID])
REFERENCES [Teams] ([ID])
GO

ALTER TABLE GamePlayers WITH CHECK ADD  CONSTRAINT [FK_GamePlayers_Teams_Private] FOREIGN KEY([PrivateTeamID])
REFERENCES [Teams] ([ID])
GO

ALTER TABLE GameCards WITH CHECK ADD  CONSTRAINT [FK_GameCards_Games] FOREIGN KEY([GameID])
REFERENCES [Games] ([ID])
GO

ALTER TABLE GameCards WITH CHECK ADD  CONSTRAINT [FK_GameCards_Cards] FOREIGN KEY([CardID])
REFERENCES [Cards] ([ID])
GO

ALTER TABLE Cards WITH CHECK ADD  CONSTRAINT [FK_Cards_Teams] FOREIGN KEY([TeamID])
REFERENCES [Teams] ([ID])
GO

ALTER TABLE GameCards WITH CHECK ADD  CONSTRAINT [FK_Cards_Players] FOREIGN KEY([GamePlayerID])
REFERENCES [GamePlayers] ([ID])
GO

ALTER TABLE GameTurns WITH CHECK ADD  CONSTRAINT [FK_GameTurns_Games] FOREIGN KEY([GameID])
REFERENCES [Games] ([ID])
GO

ALTER TABLE GameTurns WITH CHECK ADD  CONSTRAINT [FK_GameTurns_GameCards] FOREIGN KEY([GameCardID])
REFERENCES [GameCards] ([ID])
GO


insert into Teams select 'Human'
insert into Teams select 'Alien'