//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessOfElimination.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GamePlayer
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GamePlayer()
        {
            this.GameCards = new HashSet<GameCard>();
            this.ChatMessages = new HashSet<ChatMessage>();
            this.PlayerActions = new HashSet<PlayerAction>();
            this.GameTurns = new HashSet<GameTurn>();
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public string Name { get; set; }
        public string UserID { get; set; }
        public int PublicTeamID { get; set; }
        public int PrivateTeamID { get; set; }
        public string Notes { get; set; }
        public int Position { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameCard> GameCards { get; set; }
        public virtual Game Game { get; set; }
        public virtual Team PrivateTeam { get; set; }
        public virtual Team PublicTeam { get; set; }
        public virtual User User { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ChatMessage> ChatMessages { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAction> PlayerActions { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameTurn> GameTurns { get; set; }
    }
}
