//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProcessOfElimination.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GameCard
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public GameCard()
        {
            this.GameTurns = new HashSet<GameTurn>();
            this.PlayerActions = new HashSet<PlayerAction>();
        }
    
        public int ID { get; set; }
        public int GameID { get; set; }
        public int CardID { get; set; }
        public Nullable<int> GamePlayerID { get; set; }
        public int Position { get; set; }
        public bool Discarded { get; set; }
    
        public virtual Card Card { get; set; }
        public virtual GamePlayer GamePlayer { get; set; }
        public virtual Game Game { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<GameTurn> GameTurns { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PlayerAction> PlayerActions { get; set; }
    }
}
